### ISSUE TITLE
Should the Readme be updated?

### ISSUE THREAD

**Issue by DougBeney** [Pastafarianist/shutter#2]
Hello,

Glad to see that this unofficial fork is being developed actively. 

The Readme file in this repo links out to the ShutterProject website. isn't the official version no longer maintained? The latest source code available on the ShutterProject website is from 2014.

**Comment by neongreen** [comment]
Btw, the latest official release of Shutter was yesterday: https://launchpad.net/shutter/+announcement/14740.

**Comment by Pastafarianist** [comment]
@DougBeney it is not being developed actively. Initially I created this repository only to publish one fix, and a couple of weeks ago I merged one PR. That's it. I have _very_ limited knowledge of Perl and no intention to learn more of it, hence I can't contribute to the project in a substantial way.

Besides, the official project seems to be alive. If you have any more concrete suggestions, feel free to share them; otherwise I see no point in keeping this issue open.
